src/main/java/edu/ucuenca/edcontinua/entities/Curso.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucuenca.edcontinua.entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author wilson
 */
@Entity
@Table(name = "curso")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Curso.findAll", query = "SELECT c FROM Curso c"),
    @NamedQuery(name = "Curso.findByIdCurso", query = "SELECT c FROM Curso c WHERE c.idCurso = :idCurso"),
    @NamedQuery(name = "Curso.findByNombre", query = "SELECT c FROM Curso c WHERE c.nombre = :nombre"),
    @NamedQuery(name = "Curso.findByDescripccion", query = "SELECT c FROM Curso c WHERE c.descripccion = :descripccion")})
public class Curso implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 10)
    @Column(name = "id_curso")
    private String idCurso;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "nombre")
    private String nombre;
    @Size(max = 200)
    @Column(name = "descripccion")
    private String descripccion;
    @JoinColumn(name = "id_tipo", referencedColumnName = "id_tipo")
    @ManyToOne
    private Tipo idTipo;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idCurso")
    private Collection<CursoInstructor> cursoInstructorCollection;
    @OneToMany(mappedBy = "idCurso")
    private Collection<Modulo> moduloCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idCurso")
    private Collection<CursoDirigidoa> cursoDirigidoaCollection;
    @OneToMany(mappedBy = "idCurso")
    private Collection<Detalle> detalleCollection;

    public Curso() {
    }

    public Curso(String idCurso) {
        this.idCurso = idCurso;
    }

    public Curso(String idCurso, String nombre) {
        this.idCurso = idCurso;
        this.nombre = nombre;
    }

    public String getIdCurso() {
        return idCurso;
    }

    public void setIdCurso(String idCurso) {
        this.idCurso = idCurso;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripccion() {
        return descripccion;
    }

    public void setDescripccion(String descripccion) {
        this.descripccion = descripccion;
    }

    public Tipo getIdTipo() {
        return idTipo;
    }

    public void setIdTipo(Tipo idTipo) {
        this.idTipo = idTipo;
    }

    @XmlTransient
    public Collection<CursoInstructor> getCursoInstructorCollection() {
        return cursoInstructorCollection;
    }

    public void setCursoInstructorCollection(Collection<CursoInstructor> cursoInstructorCollection) {
        this.cursoInstructorCollection = cursoInstructorCollection;
    }

    @XmlTransient
    public Collection<Modulo> getModuloCollection() {
        return moduloCollection;
    }

    public void setModuloCollection(Collection<Modulo> moduloCollection) {
        this.moduloCollection = moduloCollection;
    }

    @XmlTransient
    public Collection<CursoDirigidoa> getCursoDirigidoaCollection() {
        return cursoDirigidoaCollection;
    }

    public void setCursoDirigidoaCollection(Collection<CursoDirigidoa> cursoDirigidoaCollection) {
        this.cursoDirigidoaCollection = cursoDirigidoaCollection;
    }

    @XmlTransient
    public Collection<Detalle> getDetalleCollection() {
        return detalleCollection;
    }

    public void setDetalleCollection(Collection<Detalle> detalleCollection) {
        this.detalleCollection = detalleCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idCurso != null ? idCurso.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Curso)) {
            return false;
        }
        Curso other = (Curso) object;
        if ((this.idCurso == null && other.idCurso != null) || (this.idCurso != null && !this.idCurso.equals(other.idCurso))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "edu.ucuenca.edcontinua.entities.Curso[ idCurso=" + idCurso + " ]";
    }
    
}

src/main/java/edu/ucuenca/edcontinua/controller/CursoController.java
package edu.ucuenca.edcontinua.controller;

import edu.ucuenca.edcontinua.entities.Curso;
import edu.ucuenca.edcontinua.controller.util.JsfUtil;
import edu.ucuenca.edcontinua.controller.util.JsfUtil.PersistAction;
import edu.ucuenca.edcontinua.entities.CursoDirigidoa;
import edu.ucuenca.edcontinua.entities.CursoInstructor;
import edu.ucuenca.edcontinua.entities.DirigidoA;
import edu.ucuenca.edcontinua.entities.Instructor;
import edu.ucuenca.edcontinua.entities.Modulo;
import edu.ucuenca.edcontinua.farcade.CursoFacade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import org.primefaces.event.TransferEvent;
import org.primefaces.model.DualListModel;

@Named("cursoController")
@SessionScoped
public class CursoController implements Serializable {

    @EJB
    private edu.ucuenca.edcontinua.farcade.CursoFacade ejbFacade;
    private List<Curso> items = null;
    private Curso selected;

    @EJB
    private edu.ucuenca.edcontinua.farcade.InstructorFacade ejbFacadeInstructor;
    @EJB
    private edu.ucuenca.edcontinua.farcade.ModuloFacade ejbFacadeModulo;
    @EJB
    private edu.ucuenca.edcontinua.farcade.DirigidoAFacade ejbFacadeDigido;
    @EJB
    private edu.ucuenca.edcontinua.farcade.CursoInstructorFacade ejbFacadeCursoInstructor;
    @EJB
    private edu.ucuenca.edcontinua.farcade.CursoDirigidoaFacade ejbFacadeCursoDirigidoa;
    
    
    private DualListModel<Modulo> themes;
    private Modulo theme = new Modulo();
    
    private DualListModel<DirigidoA> dirigidosa;
    private DirigidoA dirigidoa = new DirigidoA();
    
    private DualListModel<Instructor> instructores;
    private Instructor instructor = new Instructor();

    public CursoController() {
        
    }
    @PostConstruct
    public void init() {
        List<Modulo> moduls = ejbFacadeModulo.findAll();
        List<Modulo> citiesTarget = new ArrayList<Modulo>();
        themes= new DualListModel<Modulo>(moduls, citiesTarget);
        
        List<DirigidoA> dirigidos = ejbFacadeDigido.findAll();
        List<DirigidoA> dirigidos2 = new ArrayList<DirigidoA>();
        dirigidosa= new DualListModel<DirigidoA>(dirigidos, dirigidos2);
        
        List<Instructor> instructores2 = ejbFacadeInstructor.findAll();
        List<Instructor> instructores3 = new ArrayList<Instructor>();
        instructores= new DualListModel<Instructor>(instructores2, instructores3);
    }

    public DualListModel<Modulo> getThemes() {
        return themes;
    }

    public DualListModel<Instructor> getInstructores() {
        return instructores;
    }

    public void setInstructores(DualListModel<Instructor> instructores) {
        this.instructores = instructores;
    }

    public Instructor getInstructor() {
        return instructor;
    }

    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }

    public void setThemes(DualListModel<Modulo> themes) {
        this.themes = themes;
    }

    public Curso getSelected() {
        return selected;
    }

    public void setSelected(Curso selected) {
        this.selected = selected;
    }

    public Modulo getTheme() {
        return theme;
    }

    public void setTheme(Modulo theme) {
        this.theme = theme;
    }

    public DualListModel<DirigidoA> getDirigidosa() {
        return dirigidosa;
    }

    public void setDirigidosa(DualListModel<DirigidoA> dirigidosa) {
        this.dirigidosa = dirigidosa;
    }

    public DirigidoA getDirigidoa() {
        return dirigidoa;
    }

    public void setDirigidoa(DirigidoA dirigidoa) {
        this.dirigidoa = dirigidoa;
    }
    
    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private CursoFacade getFacade() {
        return ejbFacade;
    }

    public Curso prepareCreate() {
        selected = new Curso();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("CursoCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("CursoUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("CursoDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Curso> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }/*
    public List<Curso> getItemsInstructor() {
        List<CursoInstructor> findWhere = ejbFacadeInstructor.findWhere("SELECT distinct w FROM CursoInstructor w WHERE w.idCurso.idCurso='"+selected.getIdCurso()+"'");
        
        List<Instructor> itemsIns = new ArrayList<Instructor>();
        for(int i=0; i<findWhere.size(); i++){
            itemsIns.add(findWhere.get(i).getIdInstructor());
        }
        
            
        InstructorController instructorController=new InstructorController();
        instructorController.SetItemsWhere(itemsIns);
        return items;
    }*/
    public List<Curso> getItemsInstructor(Curso selected) {
       
        //SELECT distinct w FROM WsLibro w WHERE w.titulo like '%"+titulo+"%' order by w.mfn
        /*
        List<CursoInstructor> findWhere = ejbFacadeInstructor.findWhere("SELECT distinct w FROM CursoInstructor w WHERE w.idCurso.idCurso='"+selected.getIdCurso()+"'");
        
        List<Instructor> itemsIns = new ArrayList<Instructor>();
        for(int i=0; i<findWhere.size(); i++){
            itemsIns.add(findWhere.get(i).getIdInstructor());
        }
        
            
        InstructorController instructorController=new InstructorController();
        instructorController.SetItemsWhere(itemsIns);*/
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                    
                    GuardarInstructor();
                    GuardarDirigidoa();
                    
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Curso getCurso(java.lang.String id) {
        return getFacade().find(id);
    }

    public List<Curso> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Curso> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Curso.class)
    public static class CursoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CursoController controller = (CursoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "cursoController");
            return controller.getCurso(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Curso) {
                Curso o = (Curso) object;
                return getStringKey(o.getIdCurso());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Curso.class.getName()});
                return null;
            }
        }

    }
    
    public void onTransfer(TransferEvent event) {
        StringBuilder builder = new StringBuilder();
        for(Object item : event.getItems()) {
            builder.append(((Modulo) item).getNombre()).append("<br />");
        }
         

src/main/webapp/curso/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CursoCreateDlg" widgetVar="CursoCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateCursoTitle}">
            <h:form id="CursoCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{cursoController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateCursoLabel_idCurso}" for="idCurso" />
                        <p:inputText id="idCurso" value="#{cursoController.selected.idCurso}" title="#{bundle.CreateCursoTitle_idCurso}" required="true" requiredMessage="#{bundle.CreateCursoRequiredMessage_idCurso}"/>
                        <p:outputLabel value="#{bundle.CreateCursoLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{cursoController.selected.nombre}" title="#{bundle.CreateCursoTitle_nombre}" required="true" requiredMessage="#{bundle.CreateCursoRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.CreateCursoLabel_descripccion}" for="descripccion" />
                        <p:inputText id="descripccion" value="#{cursoController.selected.descripccion}" title="#{bundle.CreateCursoTitle_descripccion}" />
                        <p:outputLabel value="#{bundle.CreateCursoLabel_idTipo}" for="idTipo" />
                        <p:selectOneMenu id="idTipo" value="#{cursoController.selected.idTipo}" >
                            <f:selectItems value="#{tipoController.itemsAvailableSelectOne}"
                                           var="idTipoItem"
                                           itemValue="#{idTipoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                                        <p:tabView>
                        <p:tab>
                            <h:form>
                                <p:growl id="msg" showDetail="true" escape="false" />

                                <h3>Dirigido A:</h3>
                                <p:pickList id="pojoPickList" value="#{cursoController.dirigidosa}" var="theme" effect="bounce"
                                            itemValue="#{theme}" converter="dirigidoaConverter"
                                                showSourceControls="true" showTargetControls="true" showCheckbox="true"
                                showSourceFilter="true" showTargetFilter="true" filterMatchMode="contains" itemLabel="#{theme.nombre}">

                                    <f:facet name="sourceCaption">Available</f:facet>
                                    <f:facet name="targetCaption">Starting</f:facet>

                                    <p:ajax event="transfer" listener="#{cursoController.onTransfer}" update="msg" />

                                    <p:column style="width:25%">
                                        <h:outputText styleClass="ui-theme ui-theme-#{theme.nombre}" />
                                    </p:column>

                                     <p:column style="width:75%;">
                                        #{theme.nombre}
                                    </p:column>
                                </p:pickList>

                                <p:commandButton id="pojoSubmit" value="Submit" update="displayPlayers" oncomplete="playerDialog.show()" style="margin-top:5px"/>

                                 <p:dialog modal="true" showEffect="fade" hideEffect="fade" widgetVar="playerDialog">
                                    <h:panelGrid id="displayPlayers" columns="2">
                                        <h:outputText value="Source: " style="font-weight:bold"/>
                                        <ui:repeat value="#{cursoController.dirigidosa.source}" var="player">
                                            <h:outputText value="#{theme.nombre}" style="margin-right:5px" />
                                        </ui:repeat>

                                        <h:outputText value="Target: " style="font-weight:bold"/>
                                        <ui:repeat value="#{cursoController.dirigidosa.target}" var="player">
                                            <h:outputText value="#{theme.nombre}" style="margin-right:5px" />
                                        </ui:repeat>
                                    </h:panelGrid>
                                </p:dialog>
                            </h:form>
                        </p:tab>
                        <p:tab>
                            <h:form>
                                <p:growl id="msg" showDetail="true" escape="false" />

                                <h3>Instructor:</h3>
                                <p:pickList id="pojoPickList" value="#{cursoController.instructores}" var="theme" effect="bounce"
                                            itemValue="#{theme}" converter="instructorConverter"
                                                showSourceControls="true" showTargetControls="true" showCheckbox="true"
                                showSourceFilter="true" showTargetFilter="true" filterMatchMode="contains" itemLabel="#{theme.nombre}">

                                    <f:facet name="sourceCaption">Available</f:facet>
                                    <f:facet name="targetCaption">Starting</f:facet>

                                    <p:ajax event="transfer" listener="#{cursoController.onTransfer}" update="msg" />

                                    <p:column style="width:25%">
                                        <h:outputText styleClass="ui-theme ui-theme-#{theme.nombre}" />
                                    </p:column>

                                     <p:column style="width:75%;">
                                        #{theme.nombre}
                                    </p:column>
                                </p:pickList>

                                <p:commandButton id="pojoSubmit" value="Submit" update="displayPlayers" oncomplete="playerDialog.show()" style="margin-top:5px"/>

                                 <p:dialog modal="true" showEffect="fade" hideEffect="fade" widgetVar="playerDialog">
                                    <h:panelGrid id="displayPlayers" columns="2">
                                        <h:outputText value="Source: " style="font-weight:bold"/>
                                        <ui:repeat value="#{cursoController.instructores.source}" var="player">
                                            <h:outputText value="#{theme.nombre}" style="margin-right:5px" />
                                        </ui:repeat>

                                        <h:outputText value="Target: " style="font-weight:bold"/>
                                        <ui:repeat value="#{cursoController.instructores.target}" var="player">
                                            <h:outputText value="#{theme.nombre}" style="margin-right:5px" />
                                        </ui:repeat>
                                    </h:panelGrid>
                                </p:dialog>
                            </h:form>
                        </p:tab>
                       
                    </p:tabView>
                    <p:commandButton actionListener="#{cursoController.create}" value="#{bundle.Save}" update="display,:CursoListForm:datalist,:growl" oncomplete="handleSubmit(args,'CursoCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="CursoCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/curso/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CursoEditDlg" widgetVar="CursoEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditCursoTitle}">
            <h:form id="CursoEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{cursoController.selected != null}">
                        <p:outputLabel value="#{bundle.EditCursoLabel_idCurso}" for="idCurso" />
                        <p:inputText id="idCurso" value="#{cursoController.selected.idCurso}" title="#{bundle.EditCursoTitle_idCurso}" required="true" requiredMessage="#{bundle.EditCursoRequiredMessage_idCurso}"/>
                        <p:outputLabel value="#{bundle.EditCursoLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{cursoController.selected.nombre}" title="#{bundle.EditCursoTitle_nombre}" required="true" requiredMessage="#{bundle.EditCursoRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.EditCursoLabel_descripccion}" for="descripccion" />
                        <p:inputText id="descripccion" value="#{cursoController.selected.descripccion}" title="#{bundle.EditCursoTitle_descripccion}" />
                        <p:outputLabel value="#{bundle.EditCursoLabel_idTipo}" for="idTipo" />
                        <p:selectOneMenu id="idTipo" value="#{cursoController.selected.idTipo}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{tipoController.itemsAvailableSelectOne}"
                                           var="idTipoItem"
                                           itemValue="#{idTipoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{cursoController.update}" value="#{bundle.Save}" update="display,:CursoListForm:datalist,:growl" oncomplete="handleSubmit(args, 'CursoEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="CursoEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/curso/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CursoViewDlg" widgetVar="CursoViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewCursoTitle}">
            <h:form id="CursoViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{cursoController.selected != null}">
                        <h:outputText value="#{bundle.ViewCursoLabel_idCurso}"/>
                        <h:outputText value="#{cursoController.selected.idCurso}" title="#{bundle.ViewCursoTitle_idCurso}"/>
                        <h:outputText value="#{bundle.ViewCursoLabel_nombre}"/>
                        <h:outputText value="#{cursoController.selected.nombre}" title="#{bundle.ViewCursoTitle_nombre}"/>
                        <h:outputText value="#{bundle.ViewCursoLabel_descripccion}"/>
                        <h:outputText value="#{cursoController.selected.descripccion}" title="#{bundle.ViewCursoTitle_descripccion}"/>
                        <h:outputText value="#{bundle.ViewCursoLabel_idTipo}"/>
                        <h:outputText value="#{cursoController.selected.idTipo}" title="#{bundle.ViewCursoTitle_idTipo}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="CursoViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>